---
- name: Pull Spring image of Review App
  hosts: all
  tasks:
    - name: Pull app image
      docker_image:
        name: rajatkumariiitb/startup_review-react
        source: pull
    - name: Running the container
      docker_container:
        name: startupreview-react
        image: rajatkumariiitb/startup_review-react:latest
        state: started
        restart: yes
        ports:
          - "3000:3000"

#        volumes:
#          - /data/db:/var/lib/postgresql
#          - /data/log:/var/log/postgresql